apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
  namespace: dev
  annotations:
      circleci.com/project-id: 17f9c213-6f72-47b8-afe6-0b11f2cd71f0
  labels:
      circleci.com/component-name: my-k8s-app
      circleci.com/version: 1.0.0
      app: my-k8s-app
spec:
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        circleci.com/component-name: my-k8s-app
        circleci.com/version: 1.0.0
    spec:
      containers:
      - name: my-container
        image: oladedji/my-k8s-app:dev
        ports:
        - containerPort: 3000
